name: fiesta
channels:
  - defaults
dependencies:
  - python=3.7
  - flask
  - flask-cors
  - flask-socketio=4.3.2
  - python-engineio=3.13.2
  - python-socketio=4.6.1
  - requests
  - gunicorn
  - eventlet=0.30.2
