name: fiesta
channels:
  - defaults
dependencies:
  - python=3.9.13
  - flask=2.0.0
  - flask-cors=3.0.10
  - flask-socketio=4.3.2
  - python-engineio=3.13.2
  - python-socketio=4.6.1
  - requests=2.28.1
  - gunicorn=20.1.0
  - eventlet=0.30.2
  - pytest=7.1.2
