name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.1.1 
        with:
          activate-environment: fiesta
          environment-file: fiesta-back/environment.yml

      - name: Pytest
        run: |
          cd fiesta-back
          /usr/share/miniconda/condabin/conda activate fiesta
          pytest -s

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build angular
        run: |
          cd fiesta-front 
          npm install -g @angular/cli
          npm install --save-dev @angular-devkit/build-angular
          ng build --prod

      - name: Build and push Docker image
        run: docker build . --tag alelouis/web-fiesta:dev --push



