name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # Builds the statics files and the Docker image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkint out
        uses: actions/checkout@v2
        
      - name: Build angular
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        run: |
          cd fiesta-front 
          npm install -g @angular/cli
          npm install --save-dev @angular-devkit/build-angular
          ng build --prod

      - name: Build and push Docker image
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/setup-qemu-action@v1
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
        run: docker build . --tag alelouis/web-fiesta:latest --push

      - name: Pytest
        uses: conda-incubator/setup-miniconda@v2.1.1
        run: |
        cd fiesta-front 
        npm install -g @angular/cli
        npm install --save-dev @angular-devkit/build-angular
        ng build --prod

